# -*- coding: utf-8 -*-
"""Student Performance Analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CJgYSkWIMarjGgT54qSDHkWr2ENvXMnW
"""

import pandas as pd
import numpy as np

df = pd.read_csv("student_exam_scores.csv")
df.describe()

df.head(10)

df.tail(10)

df.shape

df.isnull().sum()

df = df.drop_duplicates()

df[df['attendance_percent'] > 75]

df.info()

df[df['exam_score'] > 40]

df.sort_values(by='exam_score', ascending=False)

X = df[["exam_score"]]
y = df["hours_studied"]

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

from sklearn.metrics import mean_squared_error
mae = mean_squared_error(y_test, y_pred)
print("Mean Absolute Error:", mae)
mse = mean_squared_error(y_test, y_pred)
print("Mean Squared Error:", mse)
r2_score = model.score(X_test, y_test)
print("R-squared Score:", r2_score)

import matplotlib.pyplot as plt

plt.scatter(X_train, y_train, color='blue', label='Training Data')
plt.scatter(X_test, y_test, color='green', label='Testing Data')
plt.plot(X_test, y_pred, color='red', linewidth=2, label='Regression Line')
plt.xlabel('Exam Score')
plt.ylabel('Hours Studied')
plt.title('Linear Regression Model')
plt.legend()

results = pd.DataFrame({'Actual': y_test, 'Predicted': y_pred})
print(results)